INSERT INTO ${target_table} (
    "platform", "business_type", "login", "symbol", "source_type", "region",
    "profit", "swap", "commission", "volume", "base_volume",
    "count", "ten_m_bucket_count", "tickprofitcount",
    "buy_pnl", "buy_base_volume", "buy_count",
    "sell_pnl", "sell_base_volume", "sell_count",
    "positive_pnl", "positive_base_volume", "positive_count",
    "negative_pnl", "negative_base_volume", "negative_count",
    "lotlabel_pnl_map", "lotlabel_base_volume_map", "lotlabel_count_map",
    "hold_label_pnl_map", "hold_label_base_map", "hold_label_count_map",
    "import_date", "update_time"
)
SELECT
    "platform",
    "business_type",
    "login",
    "symbol",
    "source_type",
    "region",
    "profit"::NUMERIC(18,2),
    "swap"::NUMERIC(18,2),
    "commission"::NUMERIC(18,2),
    "volume"::NUMERIC(18,6),
    "base_volume"::NUMERIC(18,6),
    "count"::INT,
    "ten_m_bucket_count"::INT,
    "tickprofitcount",
    "buy_pnl"::NUMERIC(18,2),
    "buy_base_volume"::NUMERIC(18,6),
    "buy_count"::INT,
    "sell_pnl"::NUMERIC(18,2),
    "sell_base_volume"::NUMERIC(18,6),
    "sell_count"::INT,
    "positive_pnl"::NUMERIC(18,2),
    "positive_base_volume"::NUMERIC(18,6),
    "positive_count"::INT,
    "negative_pnl"::NUMERIC(18,2),
    "negative_base_volume"::NUMERIC(18,6),
    "negative_count"::INT,
    "lotlabel_pnl_map",
    "lotlabel_base_volume_map",
    "lotlabel_count_map",
    "hold_label_pnl_map",
    "hold_label_base_map",
    "hold_label_count_map",
    '${import_date}'::DATE,
    CURRENT_TIMESTAMP
FROM ${staging_table}
ON CONFLICT ("import_date", "region", "login", "symbol", "source_type")
DO UPDATE SET
    "platform" = EXCLUDED."platform",
    "business_type" = EXCLUDED."business_type",
    "profit" = EXCLUDED."profit",
    "swap" = EXCLUDED."swap",
    "commission" = EXCLUDED."commission",
    "volume" = EXCLUDED."volume",
    "base_volume" = EXCLUDED."base_volume",
    "count" = EXCLUDED."count",
    "ten_m_bucket_count" = EXCLUDED."ten_m_bucket_count",
    "tickprofitcount" = EXCLUDED."tickprofitcount",
    "buy_pnl" = EXCLUDED."buy_pnl",
    "buy_base_volume" = EXCLUDED."buy_base_volume",
    "buy_count" = EXCLUDED."buy_count",
    "sell_pnl" = EXCLUDED."sell_pnl",
    "sell_base_volume" = EXCLUDED."sell_base_volume",
    "sell_count" = EXCLUDED."sell_count",
    "positive_pnl" = EXCLUDED."positive_pnl",
    "positive_base_volume" = EXCLUDED."positive_base_volume",
    "positive_count" = EXCLUDED."positive_count",
    "negative_pnl" = EXCLUDED."negative_pnl",
    "negative_base_volume" = EXCLUDED."negative_base_volume",
    "negative_count" = EXCLUDED."negative_count",
    "lotlabel_pnl_map" = EXCLUDED."lotlabel_pnl_map",
    "lotlabel_base_volume_map" = EXCLUDED."lotlabel_base_volume_map",
    "lotlabel_count_map" = EXCLUDED."lotlabel_count_map",
    "hold_label_pnl_map" = EXCLUDED."hold_label_pnl_map",
    "hold_label_base_map" = EXCLUDED."hold_label_base_map",
    "hold_label_count_map" = EXCLUDED."hold_label_count_map",
    "update_time" = CURRENT_TIMESTAMP;
